### ISSUE TITLE
Comments \ Комментарии

### ISSUE THREAD

**Issue by Kleindberg** [monstra-cms/monstra#359]
It will be nice to made comments plugin avaible by the default. I can't find something usefull.

Было бы замечательно видеть плагин "Комментарии" встроенным в систему по умолчанию, причем с собственным шорт-кодом, чтобы его можно было выводить на любой странице.

**Comment by mightyhaggis** [comment]
Have you tried http://disqus.com excellent commenting system and easily included via chunk or snippet in Monstra

**Comment by lightonflux** [comment]
Isso is similar and can easily be self-hosted and integrated via snippet. 

https://posativ.org/isso/

**Comment by Awilum** [comment]
There is no need to have this future by default, because it can be added by any comments plugin for Monstra.
