### ISSUE TITLE
Republika Srpska's flag icon is not included in Monstra

### ISSUE THREAD

**Issue by Freddynic159** [monstra-cms/monstra#394]
During the installation of Monstra not shown correctly the Republika Srpska's flag icon.

![sr-flag-icon-error-monstra](https://cloud.githubusercontent.com/assets/7980100/12566532/be70bb86-c37f-11e5-836f-c209268cc04a.png)

The flag icon is not found in https://github.com/monstra-cms/monstra/tree/dev/public/assets/img/flags

I hope this very small error can be solved.
Cheers!

**Comment by neoartdoo** [comment]
That is Republic Serbia :) 

[Pull request created] (https://github.com/monstra-cms/monstra/pull/396)

**Comment by Awilum** [comment]
Seems its fixed now. closing.
