### ISSUE TITLE
php code execution in snippets modul

### ISSUE THREAD

**Issue by xiaohuihui1113** [monstra-cms/monstra#455]
Hello sir,
I have found a php code execution vulnerability in Monstra 3.0.4.Here I was able to execute PHP command.

visit: http://ip/monstra-3.0.4/admin/index.php?id=snippets&action=edit_snippet&filename=google-analytics

In this page，input <?php phpinfo()?>
example:

<img width="1011" alt="image" src="https://user-images.githubusercontent.com/22784289/44663223-7dcdc180-aa42-11e8-9ca4-64a986c419ff.png">

then visit：http://ip/monstra-3.0.4/index.php

<img width="751" alt="image" src="https://user-images.githubusercontent.com/22784289/44663361-e9179380-aa42-11e8-90e8-3be5e3503619.png">

**Comment by Awilum** [comment]
SNIPPETS CAN CREATE AND EDIT ADMIN AND TRUSTED USERS!
SNIPPETS ALLOW TO USE HTML AND PHP CODE!
